creation_rules:
  - path_regex: infra/*
    gcp_kms: projects/kitabisa-infra/locations/global/keyRings/sops/cryptoKeys/sops-key

  - path_regex: stg/*
    gcp_kms: projects/kitabisa-stg/locations/global/keyRings/sops/cryptoKeys/sops-key

  - path_regex: uat/*
    gcp_kms: projects/kitabisa-uat/locations/global/keyRings/sops/cryptoKeys/sops-key

  - path_regex: prod/*
    gcp_kms: projects/kitabisa/locations/global/keyRings/sops/cryptoKeys/sops-key
