FROM jaegertracing/all-in-one:1.22.0

ENV COLLECTOR_ZIPKIN_HTTP_PORT=9441
ENV SPAN_STORAGE_TYPE="grpc-plugin"
ENV GRPC_STORAGE_PLUGIN_BINARY="/opt/jaeger-influxdb/jaeger-influxdb-linux"
ENV GRPC_STORAGE_PLUGIN_CONFIGURATION_FILE="/opt/jaeger-influxdb/params/jaeger-influx-grpc.yaml"

COPY ./bin/jaeger-influxdb/jaeger-influxdb-linux /opt/jaeger-influxdb/jaeger-influxdb-linux
COPY ./params/jaeger-influx-grpc.yaml /opt/jaeger-influxdb/params/jaeger-influx-grpc.yaml

ENTRYPOINT ["/go/bin/all-in-one-linux"]
CMD ["--sampling.strategies-file=/etc/jaeger/sampling_strategies.json"]
